[package]
name = "ojw"
version = "0.1.0"
edition = "2018"
authors = ["bayashi_cl <bayashi.cl@gmail.com>"]
description = "A thin wrapper of Online Judge Tools"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
